import React from 'react'

const Help = () => {
  return (
    <div className="help">
      <Container>
        <h2>Contact with us</h2>
        <p>Phone: +8801712345678</p>
        <p>Email: abcdefg@e-mail.com</p>
        <p>Address: Dhaka, Bangladesh</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti ab magni quam harum, quibusdam nisi eveniet esse. Odio nisi veniam expedita enim maiores harum qui at iure ea necessitatibus esse magni unde eius eligendi commodi nam perspiciatis, ipsam, non quos rem modi dicta molestiae. Voluptatem, nam. Quasi dolorum, quis doloribus possimus eos optio? Nobis hic quidem perspiciatis delectus sit laudantium commodi culpa facere excepturi. Veritatis eius sunt qui illo odio accusamus labore, asperiores nam repellendus iste facere itaque voluptate, commodi unde sit nisi eos facilis iure ex architecto quo perspiciatis officia. Reiciendis accusamus atque sequi tempora obcaecati officia voluptas deleniti inventore magni vel, quibusdam quis provident similique architecto laudantium aspernatur omnis laborum, corrupti necessitatibus fuga! Quia perspiciatis obcaecati autem officia rerum nobis neque soluta, maiores similique quo commodi veritatis eligendi laudantium repellendus animi consequuntur corporis inventore, deleniti facilis? Reiciendis sapiente temporibus amet officia doloremque id molestiae labore distinctio, quas omnis.
        Optio illum deleniti provident! Laborum, ut a maxime voluptas quaerat voluptates odio atque ad id ratione incidunt sed commodi necessitatibus quod aspernatur distinctio optio sit deserunt provident, doloribus tenetur quis. A ipsum reprehenderit tempore quos nihil, rem, reiciendis tempora exercitationem qui veritatis adipisci! Rerum facere blanditiis cupiditate repudiandae ad quidem odit enim ea laborum ducimus quisquam, a velit, eaque excepturi voluptate mollitia magnam aliquid vero placeat nisi? Eum distinctio veniam officiis voluptates? Expedita veniam voluptatem dolore dignissimos esse perspiciatis quisquam inventore voluptas, explicabo excepturi ducimus, sed animi. Quibusdam corrupti distinctio quos veritatis officia, quidem reiciendis, provident quia est quae earum. Accusamus magnam vero dolorem distinctio magni sit ad officiis tenetur, vitae, dolorum, eum hic tempora? Dolorum ipsum sequi necessitatibus libero doloribus voluptate quasi quo consequatur, maiores ex hic itaque nam nostrum possimus commodi et adipisci totam atque consectetur tempore quod quia id? Veritatis, nesciunt ipsum dignissimos beatae aperiam dolorum molestias?
        Quaerat sint eligendi nostrum dolorum minima veritatis amet enim earum minus dicta maiores consectetur delectus voluptate laudantium tempora exercitationem magnam repellendus, sequi atque ipsam obcaecati error maxime dolor facilis! Ex quae repellendus incidunt accusamus illo, est dolores? Natus, delectus aspernatur ullam at nulla ipsa nemo quisquam eaque quod, sunt ratione! Qui debitis, quos incidunt placeat neque suscipit sequi commodi laboriosam hic quaerat quod distinctio laudantium odit natus labore architecto, corrupti dolorem perferendis veritatis reiciendis. Aperiam ullam sunt laborum architecto recusandae tempora nisi qui doloribus quis consequatur, tempore dolorem quaerat sed excepturi voluptate? Atque pariatur aut illum id minus adipisci reprehenderit sit! Ad, consequuntur deleniti vero eligendi non quibusdam vitae adipisci quas eius earum sint consectetur deserunt quasi, dolor provident. Alias tempore dolor veritatis? Velit quam esse vero fugit molestiae at repellendus sint pariatur ullam, molestias iusto illo nulla aliquam aperiam illum similique cumque, ad explicabo quisquam. Accusantium porro quaerat praesentium!
        Incidunt adipisci, culpa magnam in, voluptatum quo non repellat veritatis commodi laudantium inventore tempore placeat corporis, consequatur ratione veniam suscipit autem officiis accusantium qui quos? Distinctio sed suscipit maxime dolorem neque, esse accusamus exercitationem! Obcaecati ipsam, reiciendis praesentium aut mollitia cum commodi molestias porro temporibus rem quae! Necessitatibus, delectus sequi! Non facere nulla animi ab odio? Optio a facere, neque odio sapiente repellendus ipsum laboriosam! Labore nihil iusto commodi incidunt, illo eaque illum nesciunt explicabo quas iure repellat quod beatae, non odio excepturi maiores culpa praesentium similique eligendi quasi, recusandae sunt inventore? Aperiam eum quisquam deserunt atque repellendus, possimus magnam labore. Voluptates dolorum temporibus qui accusamus veniam. Reprehenderit ducimus harum earum accusantium, sed assumenda repudiandae facere. Pariatur ex dicta, minima eligendi magni ut. Repellat sit molestias non, amet nihil, odit itaque veritatis autem hic magni eos inventore harum. Quaerat ratione dicta similique, perspiciatis animi facere ut provident est illo eos!
        Porro debitis corporis, soluta magni totam iusto eius facilis magnam labore ullam asperiores quia officiis rem id explicabo impedit possimus quibusdam delectus ea doloribus expedita. Cum ullam reprehenderit sint, vero sequi autem at sit repellat cumque dignissimos possimus voluptatibus voluptatem maiores porro! Non eaque optio, enim accusamus laudantium veritatis. Distinctio quisquam minima, quasi quam magnam magni tempora expedita eligendi, impedit consectetur porro quo accusantium excepturi nemo modi officiis nisi ipsam molestias velit blanditiis temporibus. Laborum, omnis nemo dolorem aspernatur ea similique corporis illo molestias modi, error incidunt ut aliquam a. Deleniti accusamus, sapiente iure facilis, debitis vero placeat ab tempora dolor, saepe non tempore sed adipisci. Quaerat, velit! Suscipit maxime fugit minima modi rerum sint itaque quidem quo? Dolor cum nisi quibusdam labore eveniet voluptates tenetur magnam dolore quos nobis, reiciendis consequuntur expedita tempore eaque quis totam sint hic quam, delectus pariatur nam suscipit reprehenderit assumenda sequi? Nam, sapiente repellendus.
        Dicta voluptates unde obcaecati hic facere, voluptas provident itaque quae iusto, ipsa nihil corporis labore quaerat quidem possimus eos. Eum expedita iste illo saepe suscipit assumenda laboriosam itaque odio consectetur molestiae eligendi rerum fugiat ullam nulla, illum facere neque qui, debitis reiciendis omnis, molestias dolores eos? Perspiciatis inventore fuga fugiat incidunt amet, eveniet, quam nulla, veritatis voluptas id delectus architecto ex nam. Non vero suscipit facere, hic excepturi nam nihil illo culpa architecto nisi blanditiis libero laborum. Hic impedit veniam possimus ad fuga voluptatem! Natus veniam, quidem quia sit ex dolorum recusandae aliquam voluptates nulla cumque sint fugit culpa voluptatum corrupti tempora impedit quam adipisci asperiores sed omnis a delectus repellat numquam earum. Nam suscipit nisi illum ratione quidem temporibus, magnam maxime animi possimus alias enim eos eveniet aliquam impedit necessitatibus rem atque veritatis, nihil dolor similique doloremque modi error ducimus. Amet perspiciatis, deserunt nostrum eos quia accusamus? Totam, molestias.
        Beatae nisi placeat error magnam distinctio impedit modi deleniti consequatur, itaque iusto voluptatum inventore illum rerum vero enim, neque ducimus assumenda sapiente animi excepturi minus. Repellat sapiente similique iure rem fuga recusandae, nesciunt, magnam animi accusantium non nisi qui soluta, id consequatur dolores possimus. Perspiciatis tempore ipsum ratione velit facere illo fugit. Quo ratione ullam rem, tenetur enim ex. Facere sit corrupti distinctio adipisci maxime deserunt repellendus voluptate? Neque ea pariatur magnam quo minima autem distinctio, iste atque, ipsam consectetur iusto quam! Ad ducimus cum amet ex non ea sint optio repellat aliquam recusandae eum quae, consectetur reprehenderit voluptatum eos, ipsa atque! Vitae natus temporibus magnam aut dicta itaque soluta repudiandae est. Est ex quas ipsam! Corporis recusandae laborum, illum delectus sapiente officiis. Debitis quibusdam qui ipsum dignissimos, numquam incidunt eum fugiat quia iste consequatur sint repellat ullam placeat id, obcaecati porro! Distinctio pariatur repellat sed. Officiis illo iure in!
        Labore provident esse rerum, consequatur placeat aliquam magni quaerat sint pariatur minima, iste distinctio, sed veritatis debitis ut. Aut totam, odio laudantium iusto ipsum provident enim repellat animi magnam illo. Dolorum repellendus odio accusantium itaque delectus quis. Dignissimos velit quisquam error atque recusandae nulla itaque temporibus beatae quas dolorum doloremque enim, architecto deserunt alias sed ad delectus unde dolore nemo doloribus reprehenderit facere! Voluptas numquam consequatur harum porro consequuntur cupiditate corporis soluta similique tempore quam. Sint ab asperiores consequatur aliquid praesentium nihil autem sapiente, atque quos totam quisquam sequi quis sed excepturi non voluptas rem facilis temporibus saepe. Ducimus corrupti possimus aperiam, voluptatem dicta, unde, saepe eos neque earum iste repellendus et rem ratione tempore consequatur blanditiis. Corporis perferendis laborum tenetur! Accusantium repellat similique itaque perspiciatis distinctio excepturi eum deleniti labore. Numquam sint eum expedita sunt eaque porro iure sequi in nam exercitationem, omnis iusto excepturi a, beatae, assumenda ratione.
        Labore nihil maxime beatae similique, blanditiis quibusdam quos fugiat, commodi laboriosam ea sint ullam nostrum veniam deserunt necessitatibus architecto debitis tempora accusantium corrupti doloribus sapiente quaerat minima! Molestiae laborum quae totam molestias, sapiente pariatur. Recusandae dolores delectus neque adipisci rerum. Labore, nobis consectetur! Ratione velit beatae quaerat, excepturi porro consectetur deleniti culpa aliquid mollitia corporis dignissimos impedit saepe repellat quis soluta. Nihil ut itaque magni repudiandae omnis officiis, blanditiis inventore cum placeat necessitatibus distinctio optio aliquam sint. Inventore cumque rerum voluptatibus ipsum dolores? Dolorum voluptate assumenda nisi repellat impedit tempore ullam eveniet est, aliquam obcaecati culpa ad minus sit hic sapiente nesciunt error illo. Eaque labore ratione error explicabo accusantium hic maxime, accusamus expedita velit! Minima quasi alias aspernatur odio perferendis modi aliquam veniam praesentium quibusdam, ullam deleniti iure, repellendus voluptates, repellat distinctio magnam. Iure repellendus, consequuntur aut id, aliquam, nam voluptates distinctio sequi molestiae incidunt ea consequatur esse. Voluptatum!
        Itaque provident molestias earum nihil odio dicta quo voluptas magnam tenetur harum facilis veritatis placeat libero porro ab officiis, natus fugit iusto animi tempore! Ex molestias saepe error quidem beatae veniam esse magni laudantium quaerat blanditiis ducimus id doloribus repudiandae, consectetur numquam. Quisquam aspernatur ad alias minima exercitationem, a facilis temporibus, delectus dignissimos ipsa sequi velit tempora officiis. Repellat praesentium tempore eaque doloremque maiores, inventore assumenda distinctio rerum est perferendis quasi hic illo architecto temporibus non quia itaque consectetur ratione, recusandae velit! Quaerat cum nihil laborum sint accusantium voluptates labore enim repellendus quis officia officiis non nisi nemo temporibus qui nostrum, eius quasi eum architecto dolores animi amet. Recusandae accusamus dolore neque distinctio earum nobis maxime voluptate aliquid facilis atque cupiditate voluptates, libero esse saepe tenetur? Suscipit quaerat temporibus magnam ab totam cupiditate eius. Nesciunt ipsum nam fuga ducimus sapiente blanditiis nobis animi iusto quisquam, repellendus quidem, quibusdam qui nemo.</p>
      </Container>
    </div>
  )
}

export default Help